handleGHRelease: true
manifest: true
releaseType: go-yoshi
bumpMinorPreMajor: true

branches:
  - branch: main
    releaseType: go
    handleGHRelease: true
    manifest: true
    manifestFile: .release-please-manifest.json
    manifestConfig: release-please-config.json