on:
  # This allows manual activation of this action for testing.
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  INTEGRATION_TEST_INSTANCE: ${{secrets.INTEGRATION_TEST_INSTANCE}}

jobs:
  build:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: build
      run: go build -v ./...
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
          credentials_json: '${{ secrets.SPANNER_CASSANDRA_ADAPTER_CICD_SERVICE_ACCOUNT }}'

    - name: it tests against Spanner 
      run: |
          go mod tidy
          go test -v  ./... -tags=integration

    - name: it tests against Cassandra 
      run: |
          go mod tidy
          go test -v  ./... -tags=integration -target=cassandra